// HOST Platform LLC — Master Subscription Agreement
// Update CURRENT_VERSION and TERMS_TEXT here to publish a new version.
// Then use the owner console "Terms" tab to push re-sign requests to clients.

export const CURRENT_VERSION  = "MSA-v2.2-2026-05"
export const EFFECTIVE_DATE   = "May 26, 2026"
export const GOVERNING_STATE  = "Colorado"
export const ARBITRATION_CITY = "Denver, Colorado"
export const ENTITY_NAME      = "Host Platform LLC"

// ─────────────────────────────────────────────────────────────────────────────
// Full contract text — plain sections rendered by <ContractText />.
// Each entry: { heading, body } where body is plain text with \n\n for paragraphs.
// ─────────────────────────────────────────────────────────────────────────────
export interface TermsSection {
  heading: string
  body:    string
}

export const TERMS_SECTIONS: TermsSection[] = [
  {
    heading: "PARTIES AND ACCEPTANCE",
    body: `This Host Platform Subscription Agreement ("Agreement") is between Host Platform LLC, a Colorado limited liability company ("HOST," "we," "us," or "our"), and the business entity or individual identified at the time of acceptance ("Client," "you," or "your").

By clicking "I Agree," signing electronically, or using the Services, you represent that (a) you have authority to bind Client to this Agreement on behalf of the entire business entity — including all current and future restaurant locations under common ownership, management, or operation — and (b) you agree to all terms herein on behalf of that entire entity and all its locations. This constitutes a legally binding contract under the Electronic Signatures in Global and National Commerce Act (ESIGN, 15 U.S.C. § 7001), the Colorado Uniform Electronic Transactions Act (C.R.S. § 24-71.3-101), and, where applicable, the California Uniform Electronic Transactions Act (Cal. Civ. Code § 1633.1 et seq.).

Multi-Location Notice: If Client operates HOST at more than one restaurant location, a single acceptance of this Agreement — whether at any HOST station, through the signup flow, or via any other electronic acceptance method — covers and governs Client's use of the Platform at all such locations, both current and future. Client is not required to sign a separate agreement for each location.`,
  },
  {
    heading: "SECTION 1 — DEFINITIONS",
    body: `"Aggregated Data" means data derived from Client Content or Guest Data that has been combined with data from other HOST clients and de-identified so that it does not identify Client or any individual.

"Client Content" means all information, data, and materials submitted to the Platform by or on behalf of Client, including restaurant configuration, employee data, table layouts, and operational settings. Client Content does not include Guest Data generated via HOST-branded touchpoints.

"Guest Data" means all information about guests collected through or processed by the Platform, including names, phone numbers, party sizes, wait times, reservation details, visit history, and behavioral data.

"HOST Hardware" means any physical hardware provided to Client by HOST, including without limitation HOST-branded NFC signs, display stands, and mounting equipment. HOST Hardware is and remains HOST's property at all times. HOST does not provide tablets, computers, or point-of-sale terminals.

"HOST Network Data" means all data generated by, derived from, or relating to the use of the Platform across HOST's entire client network — including Aggregated Data, benchmarking data, operational analytics, queue metrics, and wait-time statistics — regardless of whether such data originated from Client Content or Guest Data.

"Order Form" means any written confirmation, plan assignment, or onboarding document issued by HOST to Client specifying the Plan, fees, hardware allocation, number of locations, and other plan-specific terms.

"Plan" means the subscription tier assigned to Client as specified in the Order Form or as updated per Section 5.3.

"Platform" means HOST's proprietary software-as-a-service waitlist, queue, and table management system, including all web interfaces, mobile interfaces, APIs, station software, NFC functionality, and any updates or modifications.

"Services" means access to the Platform and any related services HOST provides under this Agreement.

"Term" means the Initial Term and any Renewal Terms.`,
  },
  {
    heading: "SECTION 2 — SERVICES",
    body: `2.1 License. Subject to Client's compliance with this Agreement, HOST grants Client a limited, non-exclusive, non-transferable, revocable license to access and use the Platform during the Term solely for Client's internal restaurant operations at any location owned or operated by Client where Client uses the Services ("Designated Locations"). Client's acceptance of this Agreement authorizes use across all Designated Locations without requiring a separate agreement for each.

2.2 Free Plan. Under the HOST Free Plan, HOST provides: (a) Platform access at no charge; (b) two (2) HOST-branded NFC signs per restaurant location ("Signs"), which remain HOST's exclusive property; and (c) queue, waitlist, table management, and host station functionality. HOST may add new features or functionality to the Free Plan at any time without notice. HOST may remove or materially reduce existing Free Plan functionality with thirty (30) days' prior notice to Client. Routine maintenance, bug fixes, security patches, UI improvements, and all feature additions are excluded from this notice requirement and may be deployed at any time at HOST's sole discretion.

2.3 Paid Plans — Free Trial and Automatic Renewal.

AUTOMATIC RENEWAL DISCLOSURE — PLEASE READ CAREFULLY: PAID PLANS AUTOMATICALLY RENEW AND YOUR PAYMENT METHOD WILL BE CHARGED AUTOMATICALLY AT THE END OF EACH BILLING PERIOD UNLESS YOU CANCEL. BY ACCEPTING A PAID PLAN, YOU AUTHORIZE HOST TO CHARGE YOUR PAYMENT METHOD ON A RECURRING BASIS AS DESCRIBED BELOW.

Free Trial: Each paid Plan includes a thirty (30) day free trial beginning on the Effective Date. No charge applies during the trial period.

Automatic Conversion: ON DAY THIRTY-ONE (31), YOUR SUBSCRIPTION AUTOMATICALLY CONVERTS TO THE PAID PLAN YOU SELECTED AND YOUR PAYMENT METHOD WILL BE CHARGED THE APPLICABLE MONTHLY FEE (CURRENTLY $149.00/MONTH FOR THE BASE PLAN, OR AS SPECIFIED IN YOUR ORDER FORM). THIS CHARGE WILL REPEAT AUTOMATICALLY EVERY THIRTY (30) DAYS UNTIL YOU CANCEL.

Reminder Notices: HOST will send reminder notices at seven (7) and three (3) days before your trial ends and billing begins.

How to Cancel: Client may cancel at any time before day thirty-one (31) at no charge, and at any time thereafter with thirty (30) days' written notice per Section 9.3. To cancel, contact HOST in writing at the address or email on file. Cancellation stops future charges but does not entitle Client to a refund of the current billing period.

One trial per business entity. California residents: see also Section 15.1 for additional disclosures required under California's Automatic Renewal Law (Bus. & Prof. Code §§ 17600–17606).

2.4 Hardware Not Provided by HOST. HOST does not provide tablets, computers, point-of-sale hardware, monitors, or any device for running the Platform. Client is solely responsible for providing and maintaining any device used to access the Platform. HOST's hardware provision is limited to the Signs described in this Agreement and any HOST Hardware specified in an Order Form.

2.5 Modifications. HOST reserves the right to modify, update, enhance, restructure, or discontinue any feature or aspect of the Platform at any time and for any reason at HOST's sole discretion. Routine updates, bug fixes, security patches, performance improvements, UI changes, and new feature additions require no advance notice and may be deployed at any time. HOST will provide thirty (30) days' prior written notice only for changes that materially reduce the core paid functionality of a paid Plan subscription. HOST is not liable for any modification, suspension, or discontinuation of features, whether or not notice is provided.

2.6 Uptime. HOST will use commercially reasonable efforts to maintain Platform availability but does not guarantee any specific uptime percentage and is not liable for downtime caused by internet outages, third-party service failures, scheduled maintenance, or events outside HOST's reasonable control.

2.7 Multi-Location Coverage. This Agreement covers Client's use of the Platform at all current and future restaurant locations owned, operated, managed, or franchised by Client (each a "Designated Location"), regardless of the number of locations. A single electronic acceptance — whether completed at one HOST station, through the signup flow, or through any HOST-provided acceptance mechanism — is legally binding on Client's entire business entity and all its Designated Locations. Client represents and warrants that the person accepting this Agreement has authority to bind the entire business entity and all Designated Locations. Each Designated Location where Client uses the Platform is subject to the same terms, including all hardware obligations, data rights, fees, and acceptable use requirements. If Client opens new restaurant locations after the Effective Date, those locations are automatically covered by this Agreement upon first use of the Platform at that location.`,
  },
  {
    heading: "SECTION 3 — HOST HARDWARE (SIGNS)",
    body: `3.1 Ownership. All HOST Hardware, including the Signs provided under the Free Plan, is and remains the exclusive property of Host Platform LLC at all times. Client receives only a limited right to use HOST Hardware during the Term for its intended purpose. Client acquires no ownership interest in HOST Hardware under any circumstances.

3.2 Allocation. The Free Plan includes two (2) Signs per restaurant location. Additional Signs or other hardware for other Plans will be specified in the applicable Order Form.

3.3 Client Obligations. Client shall: (a) use HOST Hardware only in connection with the Platform and for its intended purpose; (b) maintain HOST Hardware in good condition (reasonable wear and tear excepted); (c) not alter, modify, deface, cover, or tamper with HOST Hardware or any HOST branding or markings; (d) not sell, transfer, pledge, or encumber HOST Hardware; (e) keep HOST Hardware at the designated location and not relocate it without HOST's prior written consent; and (f) promptly notify HOST within five (5) business days of any damage, loss, theft, or malfunction.

3.4 Loss, Damage, or Theft. Client is solely and entirely responsible for any loss, damage, theft, or destruction of HOST Hardware while in Client's possession. In such event: (a) Client must notify HOST in writing within five (5) business days; (b) Client must pay HOST's then-current replacement fee for each affected unit; (c) ALL REPLACEMENTS, REPAIRS, AND REORDERS OF HOST HARDWARE MUST BE COMPLETED EXCLUSIVELY THROUGH HOST. CLIENT MAY NOT SOURCE, FABRICATE, OR SUBSTITUTE REPLACEMENT HARDWARE FROM ANY THIRD PARTY, MANUFACTURER, OR OTHER VENDOR. ANY UNAUTHORIZED REPLACEMENT VOIDS THIS AGREEMENT WITH RESPECT TO THAT UNIT AND MAY RESULT IN TERMINATION; and (d) failure to return, account for, or pay for HOST Hardware upon or after termination entitles HOST to recover the full current replacement value per unit plus all collection costs, including reasonable attorneys' fees.

3.5 Return on Termination. Upon expiration or termination of this Agreement, Client must return all HOST Hardware to HOST within fifteen (15) days of the effective termination date, in good condition, using HOST's provided return instructions. HOST Hardware not returned within this period will be invoiced at HOST's then-current full replacement value per unit.

3.6 Risk of Loss. Risk of loss or damage to HOST Hardware passes to Client upon delivery and remains with Client until HOST Hardware is received back by HOST in good condition.

3.7 No Modifications. Client shall not physically, electronically, or programmatically modify HOST Hardware. Unauthorized modification voids all applicable warranties and may result in immediate termination.`,
  },
  {
    heading: "SECTION 4 — DATA RIGHTS AND OWNERSHIP",
    body: `4.1 Client Content. As between HOST and Client, Client retains ownership of Client Content. Client grants HOST a non-exclusive, worldwide, royalty-free license to use, store, process, copy, transmit, and modify Client Content solely to provide and improve the Services.

4.2 Guest Data — HOST Touchpoints. Client acknowledges that Guest Data generated through HOST-branded touchpoints — including HOST NFC signs, HOST QR codes, HOST web interfaces, and the HOST station — is generated by and through HOST's Platform and infrastructure. HOST owns all such Guest Data as HOST Network Data.

4.3 HOST Network Data — Ownership and Use. HOST EXCLUSIVELY OWNS ALL HOST NETWORK DATA. HOST may collect, use, analyze, license, commercialize, share, and otherwise exploit HOST Network Data for any lawful purpose without restriction, limitation, or obligation to Client, including without limitation: (a) improving, developing, and marketing the Platform and new products or services; (b) generating industry benchmarks, anonymized analytics, and research reports; (c) sharing insights with third parties including investors, partners, acquirers, and other HOST clients; (d) training, testing, and improving artificial intelligence and machine learning models; and (e) entering into data-sharing or commercialization arrangements with third-party platforms (such as reservation systems, analytics providers, or hospitality networks), on HOST's own behalf and without restaurant-by-restaurant consent. HOST's rights to HOST Network Data survive termination of this Agreement.

Where Guest Data includes personal information of California residents, HOST's collection and use of such data as described in this Section constitutes HOST's own processing as a "business" under the California Consumer Privacy Act (CCPA). HOST maintains a CCPA-compliant Privacy Policy at hostplatform.net/privacy that describes HOST's data practices and provides California residents with their rights, including the right to know, delete, correct, and opt-out of the sale or sharing of their personal information. HOST will process verifiable consumer requests in accordance with CCPA requirements and will not discriminate against any individual for exercising their CCPA rights.

4.4 Aggregated Data. HOST may at any time create Aggregated Data derived from Client Content and/or Guest Data. Upon creation, HOST exclusively owns all Aggregated Data with no restriction or obligation to Client.

4.5 Third-Party Platform Integrations. Where Client uses the Platform alongside third-party systems (such as OpenTable, Resy, Toast, or other reservation or POS platforms), Client acknowledges that: (a) HOST may need to negotiate data-sharing or integration agreements directly with such third-party platforms on HOST's own behalf, in the same manner that third-party platforms negotiate with each other rather than with individual restaurants; (b) data processed in connection with third-party integrations may be subject to those third parties' terms, and HOST is not responsible for third-party data practices; and (c) HOST's rights to HOST Network Data and Aggregated Data under this Section 4 apply to all data processed through the Platform regardless of source.

4.6 Permitted Uses by HOST. HOST may use Client Content and Guest Data to: (a) provide and improve the Services; (b) generate HOST Network Data and Aggregated Data; (c) send transactional communications (e.g., SMS wait notifications) on Client's behalf; (d) comply with legal obligations; and (e) as otherwise described in HOST's Privacy Policy.

4.7 Privacy and Consent. Client is solely responsible for: (a) complying with all applicable privacy laws in its collection and use of guest information, including the Colorado Privacy Act (C.R.S. § 6-1-1301 et seq.) and, where applicable, the California Consumer Privacy Act (Cal. Civ. Code § 1798.100 et seq.) and California Privacy Rights Act; (b) obtaining all required consents from guests and employees for HOST to process their data as described in this Agreement; (c) TCPA compliance, including obtaining prior express written consent before sending any SMS message to any guest; and (d) where Client serves California residents, ensuring Client's own privacy notices accurately describe the data practices in this Agreement, including HOST's ownership and commercialization of HOST Network Data under Section 4.3. HOST is not liable for Client's failure to comply with applicable privacy law or obtain required consents.

4.8 Security. HOST will maintain commercially reasonable security measures. In the event of a confirmed breach materially affecting Client Content or Guest Data, HOST will notify Client within 72 hours of awareness to the extent required by applicable law.

4.9 AI Training. Client acknowledges and agrees that HOST may use Client Content, Guest Data, and HOST Network Data to develop, train, test, and improve artificial intelligence and machine learning models, provided that such use complies with applicable law.`,
  },
  {
    heading: "SECTION 5 — FEES AND PAYMENT",
    body: `5.1 Free Plan. The Free Plan is provided at no charge unless and until HOST modifies it as set forth in Section 5.3.

5.2 Paid Plans. For Plans with fees, Client shall pay all amounts specified in the Order Form. Unless otherwise specified: (a) fees are due monthly in advance on the first day of each billing cycle; (b) payment is by credit card, ACH, or other HOST-approved method; (c) all fees are non-refundable except as expressly stated; and (d) fees are exclusive of taxes, which Client is responsible for.

5.3 Fee Changes. HOST may change fees or introduce fees for the Free Plan upon sixty (60) days' written notice. Continued use after such notice constitutes acceptance. If Client does not accept new fees, Client may terminate per Section 9.3.

5.4 Late Payments. Overdue amounts bear interest at 1.5% per month (18% per year) or the maximum lawful rate, whichever is less, from the due date until paid.

5.5 Suspension. HOST may suspend access upon five (5) days' notice for non-payment. Reinstatement requires payment of all overdue amounts plus a $25 reinstatement fee.

5.6 Hardware Replacement Fees. Replacement fees for HOST Hardware are separate from subscription fees and are due within fifteen (15) days of HOST's invoice. HOST may suspend Services for non-payment of Hardware replacement fees.`,
  },
  {
    heading: "SECTION 6 — INTELLECTUAL PROPERTY",
    body: `6.1 HOST IP. HOST exclusively owns all right, title, and interest in: the Platform, Services, HOST Hardware, HOST Network Data, Aggregated Data, all underlying technology, software, algorithms, interfaces, trademarks, logos, and all improvements and derivatives thereof ("HOST IP"). Nothing in this Agreement transfers any HOST IP to Client.

6.2 Client Ownership. Client owns Client Content, subject to the licenses granted to HOST in this Agreement.

6.3 Feedback. Any feedback, suggestions, or ideas Client provides regarding the Platform is assigned to HOST upon creation. HOST may use such Feedback without restriction or compensation to Client.

6.4 Restrictions. Client shall not, and shall not permit others to: (a) reverse engineer, decompile, or disassemble the Platform; (b) copy, modify, or create derivative works of the Platform; (c) use the Platform to develop a competing product or service; (d) sublicense, resell, or otherwise make the Platform available to third parties; (e) remove proprietary notices from the Platform or HOST Hardware; or (f) publish benchmarks or performance tests without HOST's prior written consent.

6.5 Trademarks. Client may not use HOST's name, logo, or trademarks without HOST's prior written approval in each instance.`,
  },
  {
    heading: "SECTION 7 — CONFIDENTIALITY",
    body: `7.1 Each party will hold the other's Confidential Information in strict confidence and not disclose it to third parties or use it for purposes outside this Agreement. Confidential Information means non-public business, financial, technical, or operational information identified as confidential or that a reasonable person would treat as confidential given the circumstances of disclosure.

7.2 Exceptions. Confidentiality obligations do not apply to information that: (a) is or becomes publicly known through no breach of this Agreement; (b) was already known to the Receiving Party without restriction; (c) is independently developed without use of Confidential Information; or (d) must be disclosed by law or court order, provided prompt notice is given to the other party.

7.3 HOST Network Data Not Confidential. HOST's collection, use, and commercialization of HOST Network Data and Aggregated Data is expressly excluded from any confidentiality obligation under this Agreement.`,
  },
  {
    heading: "SECTION 8 — WARRANTIES AND DISCLAIMERS",
    body: `8.1 Mutual Representations. Each party represents it has authority to enter this Agreement and will comply with all applicable laws in connection with its performance.

8.2 Client Representations. Client represents and warrants that: (a) Client Content does not infringe any third-party intellectual property rights or violate any law; (b) Client has obtained all required guest and employee consents for data processing described herein; (c) Client will use the Platform and HOST Hardware lawfully and in accordance with this Agreement; and (d) all information provided to HOST is accurate and complete.

8.3 HOST Disclaimer. THE PLATFORM AND SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE." TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW — INCLUDING, WITHOUT LIMITATION, CALIFORNIA CIVIL CODE § 1668 — HOST DISCLAIMS ALL WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, AND SECURITY. HOST DOES NOT WARRANT THAT THE PLATFORM WILL BE ERROR-FREE OR UNINTERRUPTED. HOST MAKES NO WARRANTY REGARDING WAIT TIME ACCURACY, TABLE TURN IMPROVEMENTS, REVENUE OUTCOMES, OR GUEST SATISFACTION RESULTS. NOTHING IN THIS SECTION DISCLAIMS LIABILITY FOR FRAUD, WILLFUL INJURY, OR VIOLATION OF LAW WHERE SUCH DISCLAIMER IS PROHIBITED BY APPLICABLE LAW.

8.4 Hardware Disclaimer. HOST HARDWARE IS PROVIDED "AS IS." HOST IS NOT RESPONSIBLE FOR CONNECTIVITY FAILURES, SIGNAL ISSUES, OR NETWORK CONDITIONS AFFECTING HOST HARDWARE PERFORMANCE.`,
  },
  {
    heading: "SECTION 9 — TERM AND TERMINATION",
    body: `9.1 Initial Term. This Agreement begins on the Effective Date and continues for the period specified in the Order Form, or month-to-month if no period is specified.

9.2 Auto-Renewal. This Agreement automatically renews for successive periods equal to the Initial Term unless either party provides written notice of non-renewal at least thirty (30) days before the end of the then-current Term. See Section 2.3 and Section 15.1 for automatic renewal disclosures.

9.3 Termination for Convenience. Either party may terminate: (a) month-to-month Plans on thirty (30) days' written notice; and (b) annual Plans on sixty (60) days' written notice, subject to any early termination fee in the Order Form.

9.4 Termination for Cause. Either party may terminate immediately upon written notice if the other: (a) materially breaches this Agreement and fails to cure within fifteen (15) days of written notice; (b) becomes insolvent, makes an assignment for the benefit of creditors, or ceases to operate; or (c) engages in fraud or willful misconduct.

9.5 Immediate Termination by HOST. HOST may terminate or suspend access immediately, without notice or liability, if Client: (a) breaches Section 3 (Hardware), Section 4 (Data), Section 6 (IP), or Section 10 (Acceptable Use); (b) fails to pay any amount due within fifteen (15) days; (c) uses the Platform for any unlawful purpose including discrimination; or (d) takes any action that creates legal, regulatory, or reputational risk to HOST.

9.6 Effect of Termination. Upon termination: (a) all licenses terminate immediately; (b) Client must return all HOST Hardware within fifteen (15) days; (c) all outstanding fees become immediately due; and (d) Sections 3.4, 3.5, 4.3, 4.4, 5 (outstanding amounts), 6, 7, 8.3, 11, 12, 13, and 14 survive termination.

9.7 Data Export. After termination, Client may export Client Content for sixty (60) days ("Export Window"). After the Export Window closes, HOST has no obligation to retain or provide access to Client Content. CLIENT IS SOLELY RESPONSIBLE FOR EXPORTING ANY DATA IT WISHES TO RETAIN BEFORE THE EXPORT WINDOW CLOSES.`,
  },
  {
    heading: "SECTION 10 — ACCEPTABLE USE",
    body: `Client shall use the Platform only for lawful internal restaurant operations at the designated location(s). Client shall not: (a) sublicense, resell, rent, or make the Platform available to third parties; (b) use the Platform to discriminate against guests on the basis of any protected characteristic under applicable law; (c) market to guests for purposes unrelated to their waitlist or reservation experience without their explicit consent; (d) interfere with or disrupt HOST's systems, networks, or infrastructure; (e) introduce malware, viruses, or harmful code into the Platform; (f) attempt to circumvent any access controls, usage limits, or security measures; (g) use automated scripts, bots, or scrapers to access the Platform; (h) use the Platform in a manner that disparages HOST or its brand; or (i) violate any applicable law or regulation.

Client is responsible for all use of the Platform by its employees, contractors, and agents ("Authorized Users") and shall ensure Authorized Users comply with this Agreement. Client must promptly notify HOST of any unauthorized access or security breach.`,
  },
  {
    heading: "SECTION 11 — LIMITATION OF LIABILITY",
    body: `11.1 No Consequential Damages. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEITHER PARTY SHALL BE LIABLE TO THE OTHER FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES — INCLUDING LOST PROFITS, LOST REVENUE, LOST DATA, BUSINESS INTERRUPTION, LOSS OF GOODWILL, OR COST OF SUBSTITUTE SERVICES — REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

11.2 Aggregate Liability Cap. EXCEPT FOR CLIENT'S INDEMNIFICATION OBLIGATIONS UNDER SECTION 12, CLIENT'S PAYMENT OBLIGATIONS FOR SUBSCRIPTION FEES AND HARDWARE REPLACEMENT FEES, AND CLAIMS ARISING FROM A PARTY'S GROSS NEGLIGENCE, WILLFUL MISCONDUCT, OR FRAUD:

(a) FOR CLIENTS ON THE FREE PLAN, HOST'S TOTAL AGGREGATE LIABILITY ARISING FROM OR RELATED TO THIS AGREEMENT SHALL BE ZERO DOLLARS ($0.00). BY ACCEPTING THE FREE PLAN, CLIENT ACKNOWLEDGES THAT HOST PROVIDES THE SERVICES AT NO CHARGE AND ASSUMES NO LIABILITY WHATSOEVER FOR LOSSES ARISING FROM USE OF OR INABILITY TO USE THE FREE PLAN SERVICES.

(b) FOR CLIENTS ON A PAID PLAN, EACH PARTY'S TOTAL CUMULATIVE LIABILITY ARISING FROM THIS AGREEMENT SHALL NOT EXCEED THE TOTAL FEES ACTUALLY PAID BY CLIENT TO HOST IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE CLAIM.

11.3 Essential Basis. The parties acknowledge that these limitations reflect a reasonable and fair allocation of risk and are an essential element of the basis of the bargain. HOST would not provide the Services without these limitations.

11.4 Claims Period. Any claim arising out of or related to this Agreement must be brought within one (1) year after the cause of action first accrued. Claims not brought within this period are permanently barred.

11.5 Hardware. HOST's liability for any HOST Hardware defect or failure is limited to repair or replacement at HOST's sole discretion. HOST is not liable for any damage to Client's property or third parties caused by HOST Hardware failure.`,
  },
  {
    heading: "SECTION 12 — INDEMNIFICATION",
    body: `12.1 By Client. Client shall defend, indemnify, and hold harmless Host Platform LLC and its affiliates, officers, directors, employees, agents, and successors (collectively, "HOST Indemnitees") from and against any and all third-party claims, actions, damages, losses, liabilities, costs, and expenses (including reasonable attorneys' fees and court costs) arising out of or relating to: (a) Client's breach or alleged breach of this Agreement; (b) Client's use or misuse of the Platform, HOST Hardware, or Services; (c) Client Content, including any claim that Client Content infringes a third party's intellectual property rights or violates any law; (d) Client's violation of any applicable law or regulation; (e) claims by guests arising from Client's operations, treatment of guests, or discriminatory practices; (f) unauthorized use of the Platform by Client's Authorized Users or any person using Client's credentials; (g) Client's failure to obtain required consents from guests or employees for data processing; or (h) injury, damage, or loss occurring at Client's physical premises.

12.2 By HOST. HOST shall defend Client against third-party claims alleging that the Platform as provided by HOST infringes a U.S. copyright or trademark, provided HOST's obligation does not apply where the infringement arises from Client Content, Client's modification of or combination with the Platform, or Client's use in violation of this Agreement.

12.3 Indemnification Process. The indemnified party must: (a) promptly notify the indemnifying party in writing of any claim; (b) grant the indemnifying party sole control of the defense and settlement; and (c) provide reasonable cooperation at the indemnifying party's expense. No settlement imposing liability on or restricting the rights of the indemnified party may be made without its prior written consent.`,
  },
  {
    heading: "SECTION 13 — DISPUTE RESOLUTION",
    body: `13.1 Informal Resolution. Before initiating formal proceedings, the parties agree to attempt good-faith negotiation for at least thirty (30) days following written notice of the dispute.

13.2 Binding Arbitration. Any dispute not resolved through informal negotiation will be finally determined by binding arbitration administered by JAMS under its Streamlined Arbitration Rules & Procedures, with one (1) arbitrator, seated in Denver, Colorado. The arbitrator's award is final and enforceable in any court of competent jurisdiction.

13.3 Class Action Waiver. CLIENT IRREVOCABLY WAIVES ANY RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION AGAINST HOST. ALL DISPUTES MUST BE RESOLVED ON AN INDIVIDUAL BASIS ONLY.

13.4 Exceptions. Either party may seek emergency injunctive or other equitable relief in any court of competent jurisdiction to prevent irreparable harm, including claims arising from misuse of HOST IP, breach of the data or hardware provisions, or breach of confidentiality obligations.

13.5 Governing Law. This Agreement is governed exclusively by the laws of the State of Colorado, without regard to conflict-of-law principles. Notwithstanding the foregoing, nothing in this Agreement limits any rights Client may have under California law that cannot be waived by contract, including any rights under California's Automatic Renewal Law (Bus. & Prof. Code §§ 17600–17606), the California Consumer Privacy Act (Cal. Civ. Code § 1798.100 et seq.), or other California consumer protection statutes, to the extent such rights apply to Client and cannot lawfully be superseded by choice-of-law provisions.

13.6 Venue. For matters not subject to arbitration, the parties consent to the exclusive jurisdiction of the state and federal courts located in Denver, Colorado.`,
  },
  {
    heading: "SECTION 14 — GENERAL PROVISIONS",
    body: `14.1 Entire Agreement. This Agreement and all applicable Order Forms constitute the entire agreement between the parties regarding its subject matter and supersede all prior and contemporaneous agreements, understandings, and negotiations.

14.2 Amendments by HOST. HOST may amend this Agreement at any time by posting the updated version at hostplatform.net/legal/terms and providing written notice to Client. Continued use of the Services after the effective date of any amendment constitutes Client's acceptance. If Client objects to a material amendment, Client's sole remedy is to terminate per Section 9.3. HOST will provide at least thirty (30) days' notice before material amendments take effect.

14.3 Assignment. Client may not assign this Agreement or any rights or obligations without HOST's prior written consent. HOST may assign this Agreement without consent in connection with a merger, acquisition, or sale of all or substantially all of its assets. This Agreement binds permitted successors and assigns.

14.4 Force Majeure. Neither party is liable for delays or failures to perform caused by events beyond its reasonable control, including acts of God, natural disasters, war, terrorism, government action, internet infrastructure outages, or third-party service provider failures.

14.5 Notices. Legal notices must be in writing and delivered by email with read-receipt confirmation, or by overnight courier, to the parties' addresses on file. Notices to HOST must be sent to HOST's designated legal contact address.

14.6 Severability. If any provision is found invalid or unenforceable, it will be modified to the minimum extent necessary to make it valid and enforceable, and all remaining provisions continue in full force.

14.7 No Waiver. Failure by either party to enforce any provision of this Agreement shall not constitute a waiver of that provision or of any other provision.

14.8 Independent Contractors. The parties are independent contractors. This Agreement does not create a partnership, joint venture, franchise, agency, or employment relationship.

14.9 No Third-Party Beneficiaries. This Agreement is for the exclusive benefit of the parties and does not create rights in any third party.

14.10 Electronic Acceptance. Client's click of "I Agree," or any other affirmative electronic indication of acceptance, constitutes Client's electronic signature and legally binding acceptance of all terms of this Agreement under ESIGN, the Colorado Uniform Electronic Transactions Act (C.R.S. § 24-71.3-101), and, where applicable, the California Uniform Electronic Transactions Act (Cal. Civ. Code § 1633.1 et seq.).`,
  },
  {
    heading: "SECTION 15 — CALIFORNIA-SPECIFIC PROVISIONS",
    body: `This Section applies to Clients whose principal place of business is located in California, or who primarily serve guests who are California residents. In the event of a conflict between this Section and any other provision of this Agreement, this Section controls with respect to California Clients.

15.1 California Automatic Renewal Law Disclosure (Bus. & Prof. Code §§ 17600–17606).

AUTOMATIC RENEWAL TERMS — CALIFORNIA CLIENTS: Your subscription will automatically renew at the end of each billing period at the then-current rate unless you cancel. The charge for each renewal period is the rate specified in your Order Form (currently $149.00/month for the Base Plan). Your subscription renews monthly (30-day periods) until cancelled. To cancel, contact HOST in writing before the next renewal date. Cancellation stops future charges; no refund is issued for the current period. You will receive a reminder notice before your free trial ends. If HOST changes the renewal price or offer terms, HOST will provide clear advance notice and the opportunity to cancel before any new charge.

Upon acceptance of a paid Plan, HOST will send you a written acknowledgment (by email) confirming these automatic renewal terms and your cancellation rights. This acknowledgment constitutes the written confirmation required under California Business and Professions Code § 17602.

15.2 California Consumer Privacy Act (Cal. Civ. Code § 1798.100 et seq.).

As described in Section 4.3, HOST operates as a "business" under CCPA with respect to Guest Data from California residents. The following applies to California Client locations:

(a) Guest Rights. California residents whose personal information is processed through the Platform have the following rights under CCPA: the right to know what personal information is collected, used, shared, or sold; the right to delete personal information; the right to correct inaccurate personal information; the right to opt-out of the sale or sharing of personal information; and the right to non-discrimination for exercising these rights. Instructions for submitting requests are available at HOST's Privacy Policy at hostplatform.net/privacy.

(b) HOST's Role. With respect to Guest Data from California residents, HOST is a "business" as defined by CCPA. HOST will maintain and make available a CCPA-compliant Privacy Policy, provide a "Do Not Sell or Share My Personal Information" mechanism as required, and respond to verifiable consumer requests within the timeframes required by CCPA.

(c) Client Obligations. Client is independently responsible for providing guests with any privacy notices required by CCPA at the point of data collection, including notice that their information may be shared with HOST and used as described in Section 4.3. Client's failure to provide required notices does not affect HOST's rights under this Agreement.

(d) Data Processing. Notwithstanding Section 4.3, to the extent that CCPA requires HOST to honor a verified California resident's request to delete or opt-out of the sale or sharing of their personal information, HOST will do so in accordance with CCPA requirements and timelines, even where such data constitutes HOST Network Data.

15.3 California Arbitration. The arbitration provisions of Section 13.2 and 13.3 are governed by the Federal Arbitration Act (9 U.S.C. § 1 et seq.) to the fullest extent permitted by law. If for any reason the FAA does not apply, California arbitration law governs.

15.4 No Unlawful Waiver. Nothing in this Agreement constitutes a waiver of any right under California law that cannot be waived by private agreement, including without limitation rights under the California Consumers Legal Remedies Act, California Unfair Competition Law, or any other applicable California statute.`,
  },
]

export const FULL_TERMS_PLAIN = TERMS_SECTIONS.map(s => `${s.heading}\n\n${s.body}`).join("\n\n---\n\n")
